places: handle cases where XDG_ dirs couldn't be resolved
tchx84/Portfolio pull request #143
Opened 2021-03-03 21:13 UTC by craftyguy

get_user_special_dirs can return None if the logical id could not be
resolved, so this change handles this case by skipping over the call to
_add_place.

Without this check, the application will crash with a TypeError when it
ultimately calls os.fspath(None).

2021-03-03 22:47 UTC, tchx84 requested changes
hey @craftyguy ,

This would be simpler and make it more robust.

```
    def _add_place(self, group, icon, name, path, mount=None):
        if not os.path.exists(path)
            return
```

2021-03-03 22:56 UTC, craftyguy commented
ok, changed.

2021-03-05 06:32 UTC, craftyguy commented
Um, actually, this doesn't work, because you're still calling `os.path.basename` on a potential `NoneType` as a param in the calls to `_add_place`. My original patch skips the call to `os.path.basename` entirely.

A 'simplified' version would be to make `self._has_permission` return `False` if the dir doesn't exist, but that doesn't seem to align with the name of that method. So I've reverted this MR back to my original patch, which solves the issue.

2021-03-05 08:47 UTC, tchx84 commented
> Um, actually, this doesn't work, because you're still calling `os.path.basename` on a potential `NoneType` as a param in the calls to `_add_place`. My original patch skips the call to `os.path.basename` entirely.
>
 
If path is None it will already short-circuit and return.

2021-03-05 09:35 UTC, craftyguy commented
With my patch, yes. With what you proposed, this will still execute (and fail): https://github.com/tchx84/Portfolio/blob/master/src/places.py#L109

since the None check is in _add_place.

2021-03-05 10:05 UTC, tchx84 commented
> With my patch, yes. With what you proposed, this will still execute (and fail): https://github.com/tchx84/Portfolio/blob/master/src/places.py#L109
> 
> since the None check is in _add_place.

:sweat_smile: right, missed that.

2021-03-05 10:10 UTC, tchx84 commented
> > With my patch, yes. With what you proposed, this will still execute (and fail): https://github.com/tchx84/Portfolio/blob/master/src/places.py#L109
> > since the None check is in _add_place.
> 
>  right, missed that.

Please just get rid of the safeguard then, as we don't need to duplicate checks.

2021-03-05 17:48 UTC, craftyguy commented
> > > With my patch, yes. With what you proposed, this will still execute (and fail): https://github.com/tchx84/Portfolio/blob/master/src/places.py#L109
> > > since the None check is in _add_place.
> > 
> > 
> > right, missed that.
> 
> Please just get rid of the safeguard then, as we don't need to duplicate checks.

oops, and I missed removing that, sorry!

It's gone now from this latest version of the patch.

2021-03-05 18:00 UTC, tchx84 approved these changes

2021-03-05 18:01 UTC, merged