Added French Translation
tchx84/Portfolio pull request #271
Opened 2022-06-20 09:42 UTC by rene-coty

I created fr.po + updated the LINGUAS file

2022-06-30 20:25 UTC, tchx84 requested changes
Thanks for this translation, just one comment regarding translation of the app's name (we shouldn't translate the name).

2022-06-30 20:25 UTC, tchx84 commented on po/fr.po
> +msgstr "Porte-documents"
I don't think we should translate the name of the app, to any arbitrary name.

2022-07-01 12:22 UTC, rene-coty commented on po/fr.po
> +msgstr "Porte-documents"
Ok, I'll change this

2022-07-04 23:06 UTC, tchx84 approved these changes

2022-07-04 23:10 UTC, merged

2022-07-04 23:10 UTC, tchx84 commented
Thank you!