Update es.po
tchx84/Portfolio pull request #284
Opened 2023-03-12 16:08 UTC by carlosgonz0

2023-03-13 12:20 UTC, tchx84 requested changes

2023-03-13 12:20 UTC, tchx84 commented on po/es.po
> +msgstr "Dispositivo disponible, ya se puede quitar"
No sería mas claro, "Ya puede quitar el dispositivo"?

Como no hay mucho espacio, es mejor mensajes cortos.

2023-03-13 23:19 UTC, carlosgonz0 commented on po/es.po
> +msgstr "Dispositivo disponible, ya se puede quitar"
sip.

2023-03-14 12:17 UTC, tchx84 commented
Merged in https://github.com/tchx84/Portfolio/commit/8665dcab9c3280c4d05e04133c3325911047a00d

2023-03-14 12:17 UTC, closed without merging