Update es.po
tchx84/Portfolio pull request #69
Opened 2021-01-02 16:54 UTC by GNUuser

2021-01-03 12:15 UTC, tchx84 commented on po/es.po
> +msgstr "Portafolio"
Hola! Prefiero no traducir el nombre.

2021-01-03 12:16 UTC, tchx84 commented on po/es.po
> +msgstr "Un gestor de archivos móvil "
¿Quizás algo que siga la misma idea?

2021-01-03 14:40 UTC, GNUuser commented on po/es.po
> +msgstr "Portafolio"
Poftfolio es un nombre genérico,  en teoría se debe traducir.  Honestamente veo muchas aplicaciones con nombres genéricos en inglés masivamente.
 Portfolio es la  única aplicacion tipo móvil, lo cual  se convierte en una aplicación-principal de gestor de archivos de posh y es mejor que tenga tradución en name.desktop para mejor intergración.
Usted es libre de cancelar mi PR.

2021-01-03 14:44 UTC, GNUuser commented on po/es.po
> +msgstr "Un gestor de archivos móvil "
"Gestor" se  adapta mejor en pantallas modo retrato. Tambien se puede usar "Admistrador" pero esta frase es muy larga para modo retrato donde el espacio es limitado a traducir.
"Administre" me parece  mal.

2021-01-03 15:47 UTC, tchx84 commented on po/es.po
> +msgstr "Un gestor de archivos móvil "
El termino gestor esta bien, la traducción se puede mejorar.

2021-01-03 15:50 UTC, tchx84 commented on po/es.po
> +msgstr "Portafolio"
> Poftfolio es un nombre genérico, en teoría se debe traducir. Honestamente veo muchas aplicaciones con nombres genéricos en inglés masivamente.
> Portfolio es la única aplicacion tipo móvil, lo cual se convierte en una aplicación-principal de gestor de archivos de posh y es mejor que tenga tradución en name.desktop para mejor intergración.
> Usted es libre de cancelar mi PR.

Y si es todo o nada, pues lo cerraré. De todos modos gracias.

2021-01-03 17:05 UTC, tchx84 commented on po/es.po
> +msgstr "Un gestor de archivos móvil "
Quizás algo como `Gestiona archivos en tu móvil`...

2021-01-06 20:05 UTC, tchx84 requested changes

2021-01-06 20:05 UTC, tchx84 commented on po/es.po
> +msgstr ""
Gestiona archivos en tu móvil ?

2021-01-06 20:05 UTC, tchx84 commented on po/es.po
> +msgstr "Acerca de"
Acerca de Portfolio ?

2021-01-06 20:05 UTC, tchx84 commented on po/es.po
> +"El logotipo de Portafolio es una versión modificada del trabajo de Jorgen "
Portfolio ?

2021-01-06 22:36 UTC, GNUuser commented on po/es.po
> +msgstr ""
Aqui si se puede un usar 'Gestiona", pero no la traduci porque no la veo en la aplicacion y talvez sea una cadena obsoleta.

2021-01-06 22:49 UTC, GNUuser commented on po/es.po
> +"El logotipo de Portafolio es una versión modificada del trabajo de Jorgen "
Voy a corregirlo a: Portfolio

2021-01-06 22:53 UTC, GNUuser commented on po/es.po
> +msgstr "Acerca de"
Para optimizar las traducciones en Portfolio se puede usar "Acerca de" en lugar de "Acerca de Portfolio".

2021-01-11 12:12 UTC, tchx84 commented on po/es.po
> +msgstr ""
Se usa la metadata que se muestra en gnome-software.

2021-01-11 12:13 UTC, tchx84 commented on po/es.po
> +msgstr "Acerca de"
Se podría, pero eso implicaría hardcodear el texto en el código y quitarlo de los archivos de Glade, lo cual es _muy_ indeseable.  Así que mejor lo dejamos asi.

2021-01-11 12:14 UTC, tchx84 commented on po/es.po
> +"El logotipo de Portafolio es una versión modificada del trabajo de Jorgen "
Ok.

2021-01-11 12:14 UTC, tchx84 requested changes
Te dejé unos comentarios.

2021-01-12 11:43 UTC, tchx84 approved these changes

2021-01-12 11:44 UTC, merged

2021-01-12 11:44 UTC, tchx84 commented
:+1: